### ISSUE TITLE
PersistGate integration

### ISSUE THREAD

**Issue by fmoessle** [redux-offline/redux-offline#145]
Hi!,

I read in the issues, that there is no integration with redux-persist v5.

But is it possible to use the PersistGate for blocking my UI to render before the store is rehydrated?

**Comment by wacii** [comment]
There is still an issue with Redux Persist v5 integration that is addressed in PRS #135 and #143, but have yet to be merged. Once that is fixed, you should be able to use v5 and `<PersistGate />`.

For now, with v4, you can use `offlineConfig.persistCallback()` to achieve the same effect.

**Comment by DaniloCouto** [comment]
So... any news about this ?

**Comment by donni106** [comment]
I think we have to use it the redux-persist v4 way: https://github.com/rt2zz/redux-persist/blob/v4.10.2/docs/recipes.md#delay-render-until-rehydration-complete

But then see https://github.com/redux-offline/redux-offline/issues/182#issuecomment-362391149 for not dispatching `persist/REHYDRATE` twice. 

Edit: hmm...but then the rehydrated state is the initial state without persisted data :(
I will give this other approach a try: http://www.petecorey.com/blog/2017/07/24/offline-graphql-queries-with-redux-offline-and-apollo/#rehydration-race-conditions

**Comment by wacii** [comment]
@DaniloCouto The mentioned PRs have been merged, so this should work. You will have to setup Redux Persist v5 yourself though. This library uses v4 by default.

**Comment by DaniloCouto** [comment]
Well, I've created my own """PersistGate""".
I created a component that holds the child components if the event 'REHYDRATE_STORE' isn't fired.

reducers/rehydrate.js

```
export default (state = false, action) => {
  switch (action.type) {
    case 'REHYDRATE_STORE':
      return true;
    default:
      return state;
  }
};
```

reducers/index.js
```
import { combineReducers } from 'redux';
...
import Rehydrate from './rehydrate'

export default combineReducers({
  ...
  rehydrate: Rehydrate,
  ....
});
```
rehydrateComponent.js

```
import React, { Component } from 'react';
import { View, ActivityIndicator } from 'react-native'; // yeap, I use react-native , but you get the idea.
import { connect } from 'react-redux';

class Rehydrate extends Component {
  render() {
    if (!this.props.rehydrate) {
      return (
        <View
          style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}
        >
          <ActivityIndicator size={'large'} />
        </View>
      );
    }
    return this.props.children;
  }
}

export default connect(state => {
  return {
    rehydrate: state.rehydrate
  };
})(Rehydrate);
```

your main js file, in my case App.js
```
  ....
  render() {
    return (
      <Provider store={store}>
        <Rehydrate>
           {/* Insert your nav components here, good luck */}
        </Rehydrate>
      </Provider>
    );
  }
  ...
```
It's a little buggy on React-native Live-reload, because sometimes the REHYDRATE_STORE event doesn't trigger.

Well, I hope I've helped someone. I'm pretty new to react.

**Comment by saiichihashimoto** [comment]
What's the state of this? Should we be making our own `PersistGate` or should there be a change in redux-offline? Or are we waiting on redux-persist?

**Comment by saiichihashimoto** [comment]
@carlosbensant's example is to redo the existing `PersistGate` functionality using the `persistCallback` (I'm assuming, it seems like that part is hidden in your `configureStore`). @wacii's suggestion is to setup your own persistor. Either way, you're reimplementing something these packages already implemented, which isn't ideal.

I think a solution that allows us to reuse existing work and more "plug and play" is the way to go. @pdpino's suggestion of exposing the redux-offline's persistor fits. And if they're up for making the necessary PR, then all the better!

I think we mostly need "sign off" on this (and how it's done) so that @pdpino's time isn't wasted.

**Comment by carlosbensant** [comment]
@saiichihashimoto Redo? What!? Nothing has been reimplemented. You misunderstood what's @wacii suggested above.

> There is still an issue with Redux Persist v5 integration that is addressed in PRS #135 and #143, but have yet to be merged. Once that is fixed, you should be able to use v5 and `<PersistGate />`.
> 
> For now, with v4, you can use `offlineConfig.persistCallback()` to achieve the same effect.

First of all, PersistGate is only available in Redux Persist v5 and this version is not officially supported by Redux Offline.

In **Redux Offline**, we already have a functionality to mimic the PersistGate behavior using `offlineConfig.persistCallback()`. This functionality is the one I'm using in my example, I'm not doing such a thing like "reimplementing something these packages already implemented.".

For clarity's sake, here is also an example of my configureStore function:

```
export default function configureStore( initialState, persistCallback ) {
    const rootReducer = combineReducers(reducers)
    const composeEnhancers = /* window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || */ compose

    return createStore(
        rootReducer,
        initialState,
        composeEnhancers(
            offline({
                ...offlineConfig,
                effect,
                discard,
                returnPromises: true,
                persistCallback: persistCallback
            }),
            applyMiddleware(
                thunk,
                logger,
                authMiddleware
            ),
        )
    )
}
```

Good night!

**Comment by saiichihashimoto** [comment]
@carlosbensant Maybe I'm misunderstanding. Even with `persistCallback`, we can't use the `<PersistGate />` that redux-persist provides, can we?

**Comment by sorodrigo** [comment]
@saiichihashimoto you are talking about `redux-persist v5` and @carlosbensant is talking about `redux-persist v4`. We allow users to disable the default `redux-persist` so that they can install externally the latest version. That said, we don't really maintain such solutions (yet). If you want to used the recommended approach you just need to use the persist provided by `redux-offline` and setup a `persistCallback`.
