### ISSUE TITLE
Persist part of redux-offline not working on Android

### ISSUE THREAD

**Issue by kbrandwijk** [redux-offline/redux-offline#154]
I have an Expo app with redux-offline. On iOS, it rehydrates perfectly fine when restarting the app. On Android, the action doesn't fire, and rehydrate doesn't happen. Are there any known issues regarding Android?

Update: upon further inspection, persist actions are also not firing...
The only thing firing is `OFFLINE/STATUS_CHANGE`, so redux-offline is initialized, but it seems the persist part isn't working.

**Comment by kbrandwijk** [comment]
Came across https://github.com/rt2zz/redux-persist/issues/102, and even though I had done so before, I removed node_modules and reinstalled everything and it started working again...

**Comment by Thrajnor** [comment]
@donni106 did you found any solution ? I'm also experiencing this problem with external android (symulator works fine)

**Comment by sorodrigo** [comment]
Have you tried https://github.com/rt2zz/redux-persist/issues/906#issuecomment-429817871 ?

**Comment by donni106** [comment]
@Thrajnor I cannot remember, sorry. But I have ejected the app a long time ago, since than it was working. So I think maybe it can be an expo version problem?
Please tell us, if the linked comment by @sorodrigo helped you.

**Comment by Thrajnor** [comment]
@donni106 too bad ;/ I found keyprefix solution a while ago, but with no luck. I can't get my to code right now but I integrate it somewhat like so:
```
const config = {
  persistOptions: {
    keyprefix: ''
  },
};
```
and added it to my `offline(config)`, and it still does not fixed my problem. Its worth to point up that i don't use expo so it shouldn't me problem with it.

From what I could dig up my problem is with `.dispatch()` not wanting to run. I will try to connect my component to store (instead of importing it) i hope it will work.

But for sure this behavior is weird because on my simulated android it works just fine, but only on my physical slightly older phones it doesn't.

I Thought it may be permission problem, but i couldn't find any confirmation.

**Comment by AntonMelentiev** [comment]
@Thrajnor did you finally found any solution? I also catch this problem. Everything works fine on the https://snack.expo.io/ but store doesn't rehydrate on the android build.
