### ISSUE TITLE
What ll be a good approach to perform the effect (item in outbox) only when on wifi and not on a data connection in mobile?

### ISSUE THREAD

**Issue by Prash88** [redux-offline/redux-offline#199]

**Comment by sorodrigo** [comment]
There’s not a way to do that without importing NetInfo in your effect and manually checking it. It’s an interesting feature request though.

I imagine maybe we could pass state as a second parameter to the peek method. This would allow you to add custom logic based on the state. And ofc the netInfo itself.

The question is whether passing state is a good idea, are there downsides to this? Cc. @wacii

**Comment by sorodrigo** [comment]
There’s still a problem with this approach. Because with `peek` you could give priority to some actions over others, but you can’t block the actions until netInfo changes. This needs to involve custom effect and discard too.

Perhaps something like this could work:
1. Decorate action with netInfo in peek.
2. Check the netInfo meta value in effect. Continue if wifi, discard if online.
3. If discard by netInfo, retry later.

Custom logic inside peek could favor actions not demanding wifi only connection.

**Comment by Prash88** [comment]
I used my own custom secondary outbox to switch items from secondary outbox to outbox when online.

**Comment by sorodrigo** [comment]
Next release will add a context param to `peek`, `enqueue` and `dequeue` where you could check netInfo. You have found an alternative, but just wanted to clarify that now this will be easier.
