### ISSUE TITLE
Better description in README

### ISSUE THREAD

**Issue by everdimension** [redux-offline/redux-offline#20]
I was unsure of what exactly this library does even after glancing over readme and listening to your lightning talk.

I'd suggest adding a couple of sentences clarifying the following:

* This library is not responsible for assets caching. You still have to use service workers and something like `sw-precache`

* This library does more than persistence. While offline, it saves all actions to a queue and tries to synchronize them when you get back online. And more importantly, it proposes an architecture for doing so.

It's nice to understand what something is for before trying to understand "how to use it".

**Comment by jevakallio** [comment]
Thanks for the feedback! I'm going to be focusing on bugfixes for the next few days, but will take this into account and clarify the intent a bit.

Ideally, I'd like to have a set of resources to point people to for applying ServiceWorker in the React stack. My own SW work has been quite bespoke and particular to the codebases I've worked in, so I'm not up to date with the latest docs and tooling. Do you have any ideas?

**Comment by jthegedus** [comment]
I've been doing a lot of digging recently on these topics on popular repos (namely create-react-app) and have found these tidbits useful:
* A create-react-app (CRA) PWA implementation: [CRA PWA](https://github.com/jeffposnick/create-react-pwa)
* The above author's PR for PWA integration into the CRA project: [PWA in CRA](https://github.com/facebookincubator/create-react-app/pull/1728)
* The initial issue thread of [PWA in CRA](https://github.com/facebookincubator/create-react-app/issues/1086)
* Also [awesome-pwa](https://github.com/hemanth/awesome-pwa#tools) is a good source of offline-first ecosystem tools
* Other tools surrounding this topic:
  * https://github.com/GoogleChrome/sw-precache
  * https://github.com/GoogleChrome/sw-helpers
  * https://github.com/GoogleChrome/sw-toolbox

Also as a newbie to React and Redux I've done a lot of documentation reading recently of all the tools that integrate with Redux (namely redux-thunk, redux-saga, redux-promise, flux-standard-action, redux-actions, ducks-modular-redux, re-ducks and reslect) and found the format of the [Reselect](https://github.com/reactjs/reselect) docs to be the easiest to follow. I believe it's because they do three fundamental things differently than most:

1. They use a popular existing example (redux todos) 
2. They explain the problem and introduce the theory of the solution at the same point (your docs do this already IMO)
3. They then show you how to go from the before to the after

I find that this helps speed up the comprehension of the paradigms they're trying to teach as well as show me why I would want to do it while helping me modify own code sooner. As a beginner, I find that it's extremely hard to learn the entire ecosystem. CRA does a great job at getting me going without config issues, but I still have to learn an entire ecosystem with new terminology and all the "recommended" tools.

**Comment by housseindjirdeh** [comment]
@jthegedus really covered a lot of the great resources available regarding SW integration in a React app. 

@addyosmani also does a great job breaking down the different ways to add offline caching to a React app [here.](https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-3-offline-support-and-network-resilience-c84db889162c#f2a2)

**Comment by jevakallio** [comment]
@housseindjirdeh that link is perfect, thank you!

**Comment by jevakallio** [comment]
Updated the README with this short disclaimer: https://github.com/jevakallio/redux-offline/blob/master/README.md#progressive-web-apps

I will eventually structure the documentation to be more browsable, and will add more direct resources then. I'm closing this issue for now, thanks all for support! In particular @jthegedus thanks for sharing your experience around learning the React ecosystem - that's valuable insight that I'll come back to when I do a next major pass on the docs 👍
