### ISSUE TITLE
Unreliable detectNetwork

### ISSUE THREAD

**Issue by olso** [redux-offline/redux-offline#24]
Consider reading

https://github.com/omnia-salud/haywire

**Comment by jevakallio** [comment]
You can already use haywire or any network detector of your choice by setting the [detectNetwork](https://github.com/jevakallio/redux-offline#change-how-network-status-is-detected) handler.

The [Offline Guide](https://github.com/jevakallio/redux-offline#is-this-thing-even-on) section also documents this:
> Sometimes, it's more reliable to check network connectivity by actually making sure you can exchange data with a remote server by periodically making a HEAD request, or keeping an open WebSocket connection with a heartbeat. 

Furthermore, we only use network detection to tell us when we are *definitely offline*, not when we are *definitely online* - the retry policy will handle retries when "online" network turns out to be not-so-online after-all.

I will want to make further improvements to the default detection strategy, but for now this is handled by configurability and docs.

Thanks for submitting the issue 🍺 !
