### ISSUE TITLE
Effect has an unexpected behavior

### ISSUE THREAD

**Issue by nnnax77** [redux-offline/redux-offline#284]
Hi, this is the actual behavior of my React Native app 

- When my Api is up, everything works as expected (**effect** is called and **commit** too)

- When my Api is down, everything works as expected (**discard** is called and **rollback** too)

- But when I switch off Wifi, the app is blocked inside the first action (effect is not called)

I've tried many configurations 

- with or without Axios

- using timeout in Axios request

- implementing Axios "cancel" request

I've tested on a real android device

My action below is called, but the effect is not triggered

```js
export function getUser(facebookid, accessToken) {
  return {
    type: GET_USER,
    payload: {
      facebookid,
      accessToken
    },
    meta: {
      offline: {
        effect: { url: `/api/users/${facebookid}`, method: 'GET', headers: { 'FBToken': accessToken } },
        commit: { type: GET_USER_SUCCESS, meta: { facebookid, accessToken } },
        rollback: { type: GET_USER_FAIL, meta: { facebookid, accessToken } }
      }
    }
  };
}
```

I probably miss something but after few days I can't figure out what's happen 
Many thanks for your help

### Store config
```js
const store = createStore(reducer,
  offline({
    ...offlineConfig,
    effect,
    discard
  })
);
```

### Offline config
```js
const effect = (effect, _action) => axios({
  ...effect,
  baseURL: url,
  responseType: 'json',
  timeout: 800
});

const discard = (error, _action, _retries) => {
  const { request, response } = error;
  if (!request) throw error; // There was an error creating the request
  if (!response) return false; // There was no response
  return 400 <= response.status && response.status < 500;
};
```

**Comment by sorodrigo** [comment]
An effect will only be tried if `offline.online` is true. This means that your actions will remain inside the outbox until you turn the wifi on.

**Comment by calumpeak** [comment]
Following on from @sorodrigo note, this is by design. Redux-offline works on 'optimistic updates'. This allows the application to react immediately to changes that would otherwise require time to hit an API endpoint. These offline actions are queued up in our `outbox` when the user is online the requests defined in the outbox are made in series and `commit`/`rollback` are emitted to allow you to consolidate the entities in your state and reflect that in the UI.
If you're offline, the requests will not be made, but you can still update state as if the user was online and redux-offline will process the outbox when the user comes back online.

Please read our segment on [write resilience](https://github.com/redux-offline/redux-offline/blob/develop/docs/basics/write-resilience.md) for more information.

**Comment by nnnax77** [comment]
it's very clear, thank you for the explanation

**Comment by AdityaTarale** [comment]
i have similar feature , where in wifi turns off and app stuck in first action what should i do ?

**Comment by sorodrigo** [comment]
If there's no connection the effect won't be performed.
