### ISSUE TITLE
offlineConfig flow issue

### ISSUE THREAD

**Issue by clems36** [redux-offline/redux-offline#285]
version 2.4.0

### Are you using `offline()` or `createOffline()` API?
offline()

### Store config
```js

const rootReducer: Reducer<IReduxState> = (state: IReduxState, action: IAction): IReduxState => {
  if (action.type === 'LOGOUT_SUCCESS' || action.type === 'PURGE') {
    console.log('Purging app...');
    state = undefined;
  }

  return mainReducer(state, action);
};

export const store: any = createStore(
  rootReducer,
  composeWithDevTools(
    applyMiddleware(reduxThunk),
    offline(offlineConfig),
  ),
);
```

### Offline config

```js
const offlineConfig = {
  ...defaultConfig,
  discard: (error, action, retries) => {
    const currentStore = store.getState();
    const errorMessage = _.get(error, 'response.data.error');
    console.log('Redux offline error:', error);
    console.log('Webservice error:', errorMessage);

    if (action.mandatory) {
      console.log('Action :', action.type, ' was already tried', retries, ' times but cant be discarded');
      return false;
    } else if (retries <= 3) {
      console.log('-----------------------------------------------------------------------------');
      console.log('Action :', action.type, ' was retried <= 3 times : Re-trying');
      console.log('-----------------------------------------------------------------------------');
      return false;
    } else {
      console.log('-----------------------------------------------------------------------------');
      console.log('Action :', action.type, ' was already tried 3 times : Discarding it');
      console.log('-----------------------------------------------------------------------------');
      return true;
    }
  },
  retry: (action, retries) => {
    return action.meta.urgent ? 100 : 1000 + (retries * 1000);
  },
  effect: (effect) => {
    return axios(effect.config);
  },
  queue: {
    ...defaultQueue,
    enqueue(outbox: IQuery[], query: IQuery) { // manages the way queries are added to the queue (outbox)

      let newOutbox = [];
      if (!isValid(outbox)) {
        newOutbox = [query]; // initialize outbox 
      } else {
        // the mandatory flag is managed in the seperate modules
        let mandatoryQueries = outbox.filter(q => q.mandatory);
        let nonMandatoryQueries = outbox.filter(q => (!q.mandatory && q.type !== query.type)); // prevents adding a non mandatory query if the same query is already in the outbox
        !query.mandatory && (nonMandatoryQueries = [...nonMandatoryQueries, query]);
        query.mandatory && (mandatoryQueries = [...mandatoryQueries, query]); // always add the query if it's mandatory
        newOutbox = [...mandatoryQueries, ...nonMandatoryQueries]; // prioritize mandatory queries over non mandatory queries
      }
      return newOutbox;
    },
    peek(outbox: IQuery[]) { // manages the next query to be sent
      const entityMaps: IEntityMap[] = _.cloneDeep(store.getState().appReducer.entityMaps);
      if (isValid(outbox) && isValid(entityMaps)) {
        entityMaps.forEach((e: IEntityMap, i) => {
          let { meta: { offline: { effect: { config: { data } } } } }: IQuery = outbox[0]; // extract the config sent to the server
          const stringify: string = JSON.stringify(data); // stringify it
          if (e.serverId && e.localId && stringify.includes(String(e.localId))) { // scan it to find a negative id
            // if the entityMaps contain the negative id and has a corresponding server id
            const replace: string = _.replace(stringify, String(e.localId), String(e.serverId)); // replace the negative id by the server id
            data = JSON.parse(replace); // switch it back to JSON format
            outbox[0].meta.offline.effect.config.data = data; // insert the new data back in the query
          }
        });
      }
      return outbox[0]; // return the newly updated query
    },
  },
  persistCallback: () => {
    console.log('Rehydration complete');
    DeviceEventEmitter.emit('rehydrationEvent', { rehydrated: true });
  },
};
```
Hi, just a quick explanation of what's going on in the offline config: we have queries that receive an id as server response. In order for the app to be able to run without waiting for the response, we fake 
that id with a negative id and insert it in the `entityMaps` array. Then once we receive the response, we insert the server id next to it's corresponding negative id and if the next query contains the negative id, we replace it in `peek`.

My problem is that sometimes (I can't reproduce the problem 100% of the time), the effect does not get called. I have logs at the webservice call, `enqueue`, `peek` and `effect` and sometimes I see all my logs correctly except in the `effect`. 

I know i'm not providing a lot of info but I was just wondering if someone had an idea of why a request can be seen in `enqueue` and `peek` but not in `effect` ...

Another question: the logs I put in `peek` are shown multiple times for the same request. So the method is called 3, 4, 5 times consecutively. I would expect it only to be called once per request.. Is that normal ?

**Comment by calumpeak** [comment]
Hi @clems36 Will see if I can help.

Regarding your problem, are you seeing it when you're online or offline? I ask this because `effect` (in this case your axios request) is the starting point for all request so I'm unsure how it can't be called 100% of the time when a user is online. If a user is offline, effect will not be called, the action will be queued to the outbox for when a user comes back online, then effect will be called.

On the issue of  `peek` being called multiple times, this is by design. Take a look [here](https://github.com/redux-offline/redux-offline/blob/develop/src/middleware.js#L22). We don't have a polling system in place to trigger the outbox to empty, we rely on actions within the application (such as our own `network\commit\rollback` actions). When an action comes through we will always call peek to get an item from the outbox, we only process that action when we're a) online and b) not currently busy/retrying another offline action. So you will see `peek` get called multiple times for one action.
Admittedly this could be cleaned up a bit so peek only gets called when we're ready to process, but at this point that would be a breaking change and would be something we'd have to consider for v3.

Further, you may find it easier to do your logic that you have in `peek` in a custom `dequeue` as dequeue will receive the the server response (commit or rollback) and have access to the outbox so there you can update the queue, change ID's for server response ID's etc - this is useful if you have relational entities (just remember to update those entities in state too 😄 ). Dequeue also has the benefit of only being called on commit/rollback, so fewer times that peek will be over the lifecycle of the middleware. I would also recommend this method as you are mutating the object in place in `peek` which, by redux's rules, is not allowed. `outbox` belongs to a reducer, and therefore should only be updated by actions, of which only `enqueue` and `dequeue` are allowed to do. State should always be immutable and predictable. We are currently improving the TS typing for redux-offline. All state is `readonly`.

**Comment by clems36** [comment]
@echoes221  Thank you for taking the time to answer. I'm seeing this issue when i'm online.

It's a little clearer why peek gets called multiple times.

About moving the logic from `peek` to `discard`, I just saw [here](https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/customize-requests.md) that I can access the server response and request from the `error` object but:

> discard will receive the the server response (commit or rollback) and have access to the outbox so there you can update the queue

do you mean accessing the `outbox` through the `action` object of `discard` ? Can I alter this object directly and replace the ID there (this seems anti-redux to me aswell as i would go on and do something like `action.meta.offline.effect.config.data. = ...`) ? Also, `discard` only gets called once `effect` fails, so that would mean I have to wait for the request to fail once before being able to send the request correctly ?

I'm aware that I'm not making correct use of the library because of some anti-redux patterns, i'm just trying to figure it out as much as I can, thanks for clearing things up already :)

**Comment by calumpeak** [comment]
@clems36 
Unsure why you're seeing this issue when you're online, most likely due to something custom in your pipeline, can debug a little further if you have an example codepen or something set up. If the item is in the outbox, then it will go through your effect if the user is online. Can you also provide an example of an offline action that you're dispatching?

Apologies for the confusion, I didn't mean discard, I meant `dequeue` (I shouldn't reply tired). I've updated my comment above to reflect that. `dequeue`'s signature is `dequeue(outbox, action, context)`, where action is the commited/rollback action, and context is the rest of the offline state. `enqueue/dequeue` are the only functions that can transform the outbox state by returning the next version of it's state e.g `return outbox.map(...)`.  You can assert whether the action that has been received is commit/rollback via `meta.success<boolean>` and `meta.completed<boolean>`

**Comment by clems36** [comment]
I think I figured it out using `dequeue`. I haven't been able to reproduce the problem and it helped me simplify a lot of other parts of the code as well. Thank you for the guidance @echoes221 !
