### ISSUE TITLE
Getting store state in `effect()`

### ISSUE THREAD

**Issue by bryanph** [redux-offline/redux-offline#292]
In my team we currently have a usecase where we need access to the store before performing the API call (to convert between local and server IDs). We currently get access to the store by passing a global object on which after configuring the store a `store` property gets set. This is a bit hacky and we would like to have a more straightforward way to pass the store.

I was wondering if it is possible to add the ability to pass the store to `effect()` (and maybe also `discard()`) to make these kinds of use-cases easier to implement and make them more predictable in their behaviour.

So this would require passing the store here:
https://github.com/redux-offline/redux-offline/blob/9e84f38be0720a069d47487eb0717b00ada11843/src/send.js#L55

**Comment by sorodrigo** [comment]
Would reading before the effect dispatches work for you? You could dispatch a `thunk` that reads the state and passes it as meta or payload to the effect.

**Comment by bryanph** [comment]
@sorodrigo Thanks for your response. I'm not sure I understand. How could reading before the `effect` dispatches work? The problem is that we need access to the store before syncing and **after** it has been added to the queue (so the moment it is pulled from the queue and is about to be synced with the server). We don't see a way to hook into this part of redux-offline whilst having access to the store in the effect callback without introducing a global variable.

**Comment by calumpeak** [comment]
@bryanph We do this at my current employ. It's a simple case of scoping and writing a custom effect. You can do something like this:

```javascript
let store;
const getStoreInstance = () => store;
const customEffect = (getStore) => (effectPayload, action) => customFetchLogic(getStore(), effectPayload, action); // Your effect logic here
const offlineConfig = {
    effect: customEffect(getStoreInstance) // Pass getStore here to your custom effect function - currying is useful here to snapshot the value
}
store = createStore(....)
```
Just make sure you check that the return value of `getStore` isn't undefined within your custom effect. I prefer passing a function instead of the variable `store` itself as it will ensure you always get a fresh copy and give a fallback if the value is actually undefined.

**Comment by bryanph** [comment]
@echoes221 yes this is what we do currently as well. Would be easier to simply pass the store instance in the redux-offline middleware to `effect` and `discard` though. I'd be happy to open a PR for this; it would be a pretty simple change.

**Comment by Xyzor** [comment]
Just what I need! :smile: 

My use case is the same, swapping local id with API's.

My approach was to switch the id  in dequeue, when the api responde with the id.  
The problem with this is that the enqueue and dequeue are in a race condition. So if I put "heavy" iteration in there, the enqueue will be called with the next action before the dequeue can return with the updated outbox.

@echoes221 I'll try your solution.

**Comment by calumpeak** [comment]
@Xyzor You shouldn't have a race condition there, only one thing can happen to the queue at one time.  And since it's synchronous in nature (the `queue` methods are run inside the reducer), it shouldn't matter. You're safe to iterate through the dequeue - you also get the current action which can contain any server info (or data you set before it even hits the server, add additional metadata to it before you even make the request!) you should have all the tools you need to iterate through, diff, squash etc.
