### ISSUE TITLE
Adding redux-offline causing MapStateToProps to run multiple times - Using Typescript

### ISSUE THREAD

**Issue by cookiekitty** [redux-offline/redux-offline#347]
### Are you using `offline()` or `createOffline()` API?
createOffline()

### Store config
Please paste your config below.
```import { Store, createStore, compose, StoreEnhancer, applyMiddleware, Reducer, AnyAction} from ‘redux’;
import { IApplicationState, createRootReducer } from ‘./store/index’;
import { createOffline } from ‘@redux-offline/redux-offline’;
import offlineConfig from ‘@redux-offline/redux-offline/lib/defaults’;

const offlineEnhancer = createOffline(offlineConfig);
const initialState = {};
export const store: Store<IApplicationState> = createStore(
   offlineEnhancer.enhanceReducer(createRootReducer()) as Reducer<IApplicationState, AnyAction>,
   initialState,
   compose(
       offlineEnhancer.enhanceStore as StoreEnhancer,
       applyMiddleware(offlineEnhancer.middleware),
   ),
);

// Config for store before redux-offline
/* export const store: Store<IApplicationState> = createStore(
   createRootReducer(),
   undefined,
); */

// This is in my Home Component
const mapStateToProps = (store: IApplicationState): IHomeProps => {
   return {
       users: store.users.users,   // Array of type "User"
       locations: store.locations.locations,  // Array of type "Location"
       passport: store.passport.passport, // Array of type "Passport"
   };
};
```

### Offline config

Are you using a custom configuration? If you are please paste your config below.
default config

**Library versions:**
“react-native”: “0.59.8"
“@redux-offline/redux-offline”: “^2.5.2"
“redux”: “^4.0.1"
“react-redux”: “^7.1.0"
"typescript": "3.5.1"

**Behavior:**
As my app is loading while using the redux-offline config (pasted above), the first component (Home) has mapStateToProps on it. This function fires 3 times as the component loads, and on the third fire, my state object loses all of its types. So "store.locations.locations" which should be an array of type "Location" instead becomes an array of general "Objects".

When I remove the above redux-offline config and switch back to the commented setup for my store, my Home component only runs mapStateToProps once when it first loads, and my types remain on my store.

I do not have any other redux-offline code setup in any of my reducers/actions (yet) as I was simply trying to make sure that setting up the store was working, first.

Is there something else I need to add to the setup, or did I configure it improperly? It seems odd to me that it would fire mapStateToProps so many times when the Home Component is not really doing anything on the initial load.

Thanks!

**Comment by calumpeak** [comment]
Hi @cookiekitty,

Let me try and go through and answer for you.

Redux-offline does a few things at startup, if you check the redux-devtools it:

 -  dispatches network online/offline (we always start in an offline state and check the network at startup)
 - dispatches rehydrate. This is the data that's being persisted being rehydrated into the store
- If there are any actions in the outbox, those also get processed and dispatched.

These actions all update the store.

Your question here is around mapState. `mapStateToProps` is called any time the [store is updated](https://react-redux.js.org/api/connect#mapstatetoprops-state-ownprops-object), the component itself will only re-render if the [props are different](https://react-redux.js.org/using-react-redux/connect-mapstate#return-values-determine-if-your-component-re-renders).

So yes, mapStateToProps will get called multiple times at startup when using redux-offline, or on any action that causes the store to update. This isn't a redux-offline specific issue, it's just that redux-offline adds a few extra actions at application start.

Regarding losing types, is this losing types in the TS sense, or the fact that the data is actually incorrect? It sounds like at runtime (since you're specifying it's on the third time) not at dev/transpile time...
