### ISSUE TITLE
Rollback always fire with Firestore

### ISSUE THREAD

**Issue by jonathanatn** [redux-offline/redux-offline#352]
I try to use Redux-Offline with Firestore, but rollback action always fire.
So the task is added to my store and after directly erased by the rollback action.

I think that the problem come from the Firestore function, because it's not an API request, it doesn't send back a correct response, so Redux-Offline assume that the connection permanently failed, and send the rollback.

Someone has an idea on how I can manage correctly my actions with Firestore? 

```js
export function addTaskAction(task) {
      return (dispatch, getState, { getFirebase, getFirestore }) => {
            const firestore = getFirestore();

            dispatch({
                  type: ADD_TASK,
                  payload: { task },
                  meta: {
                        offline: {
                              effect: firestore
                                    .collection('tasks')
                                    .doc()
                                    .set({
                                          // my properties
                                    }),
                              rollback: { type: ADD_TASK_ROLLBACK, meta: { task } }
                        }
                  }
            });
      };
}
```

**Comment by calumpeak** [comment]
Hi @jonathanatn redux offline actions are meant to be serialisable so that they can be persisted and rehydrated (e.g. strings). functions cannot be serialised correctly. If you need to handle firebase actions you'll need to write your own [effect reconciler](https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/customize-requests.md) to handle them differently. 
Something I've done in the past is use dot paths and written a reconciler to handle those in `effect` e.g.

```
meta: {
  offline: {
    effect: { path: 'path.to.api.request`, args: [] }
  }
}
```

and in the custom effect handler something like `_.get(effect.path, firestore)`.

**Comment by jonathanatn** [comment]
Thanks for your help, will give it a try!
