### ISSUE TITLE
Question about `effect` behavior

### ISSUE THREAD

**Issue by ifitzsimmons** [redux-offline/redux-offline#393]
I apologize if I've missed something fairly obvious as I am just starting to get a little experience with redux-offline. 

I am noticing that if I am connected to the internet, but the endpoint in my effect statement is unreachable, redux-offline removes the request from my outbox, since I am technically still online. 

I want to change this behavior so that, regardless of whether I am connected to the internet or not,  my offline outbox will store any request that was not successfully posted to my endpoint. 

Is there a way to modify this behavior?

**Comment by sorodrigo** [comment]
Do you want to store it in order to retry it later? Or just for analytics sake?

### If you want to attempt a retry:
Read the [discard](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#discard) section of the documentation.

### If you want to store it for analytics sake:
Add the request url as a meta attribute in the rollback action, this way you can access the failed urls when the rollback is dispatched.

**Comment by ifitzsimmons** [comment]
If I wanted to retry it later, is there a way to store the outgoing messages in the offline outbox until they are committed.

My goal is to have the actions persist in the outbox until they are committed. 

My application will allow users to make "transactions" offline. The problem is that some users have extremely poor internet connectivity. So even if they are online, they might not be able to POST those transactions. However, those "transactions" are vital to the business and MUST be sent to the backend when possible. 

Can I manually add to the offline outbox upon failure or do I need to create my own queue for ROLLBACKs and store the url with each of the ROLLBACK actions and manually submit until they are successfully submitted?

**Comment by sorodrigo** [comment]
Interesting, you have the same use case that @bradstiff does. You can check out conversation here #400
