### ISSUE TITLE
Migration to original repo

### ISSUE THREAD

**Issue by sorodrigo** [redux-offline/redux-offline#66]
Lets discuss the migration strategy.

**Comment by wacii** [comment]
Renaming this repository would redirect traffic from the current url to the new one. Which is not great considering we want to park the original repo here. Not sure what the behavior would be, but to be safe, I imagine we would have to delete this repo.

Whatever we do I'll start moving my PRs over to the main repo.

**Comment by sorodrigo** [comment]
We can close the issues here, and put a notice on the readme to go to the other one.

**Comment by piranna** [comment]
> Renaming this repository would redirect traffic from the current url to the new one. Which is not great considering we want to park the original repo here.

Redirects works so far there's no a newer repo with the same name, so it's safe to delete this one or rename it to "redux-offline-legacy", and move the community one here. Being a fork of this one it could give some problems (GitHub don't allow to have two projects one forked from another on the same user/organization), so this one would need to be deleted.

Another option would be, since this repo is already sync'ed with the community one, use a tool to move the issues and pull-requests from the community one here and delete the community one...

**Comment by sorodrigo** [comment]
We want to maintain the number of stars so everything needs to go to the original. About the name conflict, etc. I could transfer this repo outside from the org, close its issues and rename it. (I really don't want to delete it 😛 )

**Comment by piranna** [comment]
Sounds like a plan :-) Just only please move first the issues and pull-requests with something like https://github.com/google/github-issue-mover

**Comment by sorodrigo** [comment]
thanks we'll do!

**Comment by wacii** [comment]
Oh! I didn't think it was possible to move issues like that. Nice tip.

**Comment by piranna** [comment]
It's not like moving but instead copy and delete. I did it some time ago when unifying NodeOS repos.

**Comment by piranna** [comment]
What's going to happen with the open branches and pull-requests? Are they going to be moved to the other repo too (It should be)?

**Comment by sorodrigo** [comment]
@piranna Hey yes everything is moving elsewhere, I'm really slammed at work right now, will have to wait a little bit.

**Comment by sorodrigo** [comment]
I consider the repo as officially migrated. Closing.
