### ISSUE TITLE
Question: Clearing outbox?

### ISSUE THREAD

**Issue by adamjacob** [redux-offline/redux-offline#68]
I can't seem to figure out how to clear the outbox.  If a user logs out of the client I need to clear the outbox and any remaining requests.  Is there anyway to easily do this?  I have a root reducer that has a reset method where I reset the state of my whole store but the offline state doesn't reset.

**Comment by DylanGriffith** [comment]
I'm guessing based on the [updater](https://github.com/jevakallio/redux-offline/blob/master/src/updater.js) code there is probably no easy way to do this with this library. You might need to look into if `redux` in general has someway of reaching into and resetting/changing the state of other reducers.

**Comment by DylanGriffith** [comment]
On the positive side/however I suspect that all your further requests will be bounced because you're not authenticated and a `40X` response will result in them being removed from the queue.

Another option would be to update the effect reconciler to look at the authentication data and simply drop messages if the session is not available.

**Comment by dabit1** [comment]
If you look at the README.md you gonna find the solution:

```javascript
import { RESET_STATE } from "@redux-offline/redux-offline/lib/constants";
store.dispatch({ type: RESET_STATE });
```

**Comment by donni106** [comment]
**With links**

README.md:
https://github.com/redux-offline/redux-offline/tree/master#empty-the-outbox

This triggers:
https://github.com/redux-offline/redux-offline/blob/master/src/updater.js#L112-L118
