### ISSUE TITLE
Integration with Apollo

### ISSUE THREAD

**Issue by sedubois** [redux-offline/redux-offline#7]
This library looks super promising :-) 

I previously built an Apollo + Redux + Graphcool + Next.js POC and would love to add offline capability: https://github.com/relatenow/relate

How can redux-offline be combined with Apollo/Graphcool?

**Comment by funkyeah** [comment]
I've been doing some reading and research somewhat related to this question. I think it would be difficult but not impossible. Guessing some close coordination with the Apollo team would be needed.

1) On the persistance and re-hyrdration side the first issue is that the entirety of the apollo redux state is not meant to be persisted and re-hydrated. I think Apollo has the API functionality to handle this as long as it was figured out how to do it correctly.

2) Once the store has re-hydrated  with data from previously successful Graphql queries, Apollo can query that local cache. 

3) There is no built in way to tell Graphql when to fetch or re-fetch data when the client comes back on-line

4) I think the biggest issue is the batching of mutations. From the redux-offline docs:
store. 
> In order to support Write-resilience, we will store all network-bound actions in a queue inside our Redux Offline creates a state subtree called offline, where among other internal state needed by the library, it manages an array called outbox.

> To be able to perform the network-bound actions after we come back online, we need to store all necessary data to perform the action, and metadata about what should happen afterwards. 

Apollo is built on top of redux but the redux actions dispatched by query and mutation operations are abstracted from the developer. So we can't just append data to the redux actions to describe how offline should work, nor can we queue these actions up easily.

**Comment by sedubois** [comment]
@funkyeah thanks for the comments, it also looked to me like a collaboration with Apollo would be best. Maybe @stubailo can comment?

**Comment by stubailo** [comment]
I think there are two relatively issues here:

1. Apollo expects the Redux state to be initialized right away, but with this implementation it probably takes some time to get ready. That's something we can try to fix in Apollo.
2. Apollo manages your network requests for you, but not in a way that is aware of offline state. There's no easy way to queue up mutations, and there's no built-in functionality to refetch all queries when you come back online.

The first one is mostly about retaining data across reloads, but the second might require some changes in Apollo.

We have wanted to build the offline functionality for a while, but the main blocker has been a lack of clear goals. What does offline first mean? What actions need to be available offline, and what does loading data when offline look like? Because GraphQL pushes a lot of the "understanding" of data to the server which usually makes client-side data management simpler, I think it actually makes offline a bit more complex.

If you are interested in spending some time on this I'd love to help. The first step I think would be collecting some of the requirements of how it should work. What is the behavior when going on and offline? How should queueing up mutations work? Etc.

**Comment by sedubois** [comment]
@stubailo that's great feedback, thanks. Unfortunately @jevakallio [wrote](https://github.com/jevakallio/redux-offline/pull/17#issuecomment-292208117) he doesn't have as much time as he thought 😞

@rauchg also [wrote](https://github.com/zeit/next.js/issues/861#issuecomment-280155417) that offline is a top priority for Next.js.

Opportunity for collaboration perhaps.

**Comment by jevakallio** [comment]
@sedubois @stubailo thanks for your comments. I don't currently see how Apollo offline-first should work - overall I have very limited experience with Apollo, though from what I've seen it's a hella impressive piece of work!

I'm going to stop giving estimates on when I'm delivering things, but let's say _soon_ I'll put together an example app using redux-offline. I think branching off of such example, integrating with Apollo, and seeing where the friction starts to burn would be a good way to find out.

If anybody has the time to set up a general redux-offline example app that follows the basic documentations in README, that would be a great starter.

**Comment by philohelp** [comment]
Apollo + redux-offline would be absolutely amazing ! I'll try to do the example.

**Comment by ManAnRuck** [comment]
I have try to start a simple example with redux-offline & apollo. 
I would be happy about changes.

https://github.com/ReggaePanda/redux-offline-examples

**Comment by notrab** [comment]
I'd recommend you have a read of http://www.east5th.co/blog/2017/07/24/offline-graphql-queries-with-redux-offline-and-apollo/ for a way to do this 😀

**Comment by witbybit** [comment]
Thanks for sharing this article @notrab. When is the next article coming out for mutations?

**Comment by notrab** [comment]
Hi @nikhilag - I didn't write this article - I'm sure comments are enabled for that post though 👍

**Comment by developer239** [comment]
I have simple workbox-webpack-react-apollo-graphql implementation here: https://github.com/developer239/workbox-webpack-react/tree/with-apollo-graphql Note that graphql is not in master branch of the respository.

It works pretty nice. Now I am trying to figure out how to "reload" apollo query after user gets back online.

1) Workbox prefetches html / js files
2) User can load homepage even offline
3) User goes to graphql blog section
a) If user visited this section before he should be able to see latest blog posts
b) If not I show network connection error message
4) If user stays in graphql blog section and makes his internet working I would love to reload the page so that he can see latest post. Should I use subscriptions? Or is that a work for workbox / redux-offline?

**Comment by PaulBrachmann** [comment]
Hey @developer239,
if you want to refetch your Apollo query once, immediately after the user came back online, you could listen to redux-offline's default ```config.detectNetwork``` method (or, if necessary, [a custom one](https://github.com/jevakallio/redux-offline#change-how-network-status-is-detected)) and just manually execute your query again (using [```client.query()```](http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient\.query)).

If you want your users to see live updates whenever a new blog post is published, you'll want to look into GraphQL subscriptions (depending on your implementation, what I've suggested above might still be necessary).

Note that the aforementioned solution is a workaround that works best if only used for a small number of queries (otherwise you might lose track of what needs to be refetched - and what maybe doesn't). I'm planning on adding a more convenient way of implementing that sort of refetch behaviour to a package that provides an offline-first toolkit specifically for Apollo, [apollo-offline](https://github.com/Malpaux/apollo-offline). It is built on top of redux-offline and my attempt at plug-and-play offline support for Apollo apps.

**Comment by developer239** [comment]
@MLPXBrachmann Wow apollo-offline looks promising. I will look at it tomorrow and post some feedback here. :)
