### ISSUE TITLE
There is a way to call multiple dispatch in commit and rollback?

### ISSUE THREAD

**Issue by jose920405** [redux-offline/redux-offline#75]
Previously i used callbacks for the request, and there was something like this, when the request was success.

```
if (isSuccess) {
    dispatch({ type: ITEMS_SUCCESS, isPaging: params.isPaging, categoryId: catId, data: response });
    if (key == 'x') {
        dispatch({ type: SET_PAGE_X, page: params.page + 1 }); //External Dispatch (to other reducer)
    } else {
        dispatch({ type: SET_PAGE_Y, page: params.page + 1 }); //External Dispatch (to other reducer)
    }
}
```

this library only accept one dispatch `commit: Action`. Exist a way for send multiples?

**Comment by DylanGriffith** [comment]
@jose920405 the only options I know for doing that with this library are not super trivial.

One way you can accomplish this is by [configuring a custom effect reconciler](https://github.com/jevakallio/redux-offline#change-how-network-requests-are-made) and pass the dispatch to the effect reconciler (someone described how to do that [here](https://github.com/jevakallio/redux-offline/issues/35)). That being said it's a little bit complicated to do that as far as I know using this `redux-offline`. Depending on how important further dispatches is to you, I'd recommend just trying to see if you can make the single dispatch work for you because ultimately it will make your code simpler to test and maintain longer term.
